### ISSUE TITLE
[IP Banned] Appeal Request

### ISSUE THREAD

**Issue by xslidian** [SukkaLab/Report#1]
## Info

- **IP Address**: `207.241.226.230`
- **Country**: `US`
- **Ray ID**: `4daa854178786e06`

## Message

`207.241.224.0/20` and `208.70.24.0/21` belong to the Internet Archive ([AS7941](https://ipinfo.io/AS7941)), aka the Wayback Machine. It helps preserving webpages in case they vanish in the future.

**Comment by SukkaW** [comment]
Sorry for the inconvenience.
Since `Internet Archive` has behaved like bad crawler for several times (Send hundreds of requests in minutes), I have to block the whole `AS7941` completely.
If you have to archive any content for specific reasons, I suggest using submit archive request manually at https://archive.is .

**Comment by xslidian** [comment]
Thanks for the reply. 
Now that it's an intended behavior, this report is no longer necessary to remain open.
